title: Default
navigation:
    status: all
    template: all


columns:
  # main
  main:
    width: 2/3
    sections:

      # a simple form
      content:
        type: fields
        fields:
          pagenm:
            label: Headline
            type: text
          text:
            label: Text
            type: textarea
            size: medium

  # sidebar
  sidebar:
    width: 1/3
    sections:

      # a list of subpages
      pages:
        type: pages
        headline: Subpages

      # a list of files
      files:
        type: files
        headline: Files